on:
  push:
    branches:
      - main
jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_DEPLOYMENT_SERVICE_ACCOUNT }}'


    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'function-eurojackpot'
        runtime: 'python310'
        entry_point: 'hello_pubsub'
        memory_db: '128'
        env_vars: 'SENDER_EMAIL=${{ secrets.SENDER_EMAIL }},RECIPIENT_EMAILS=${{ secrets.RECIPIENT_EMAILS }}'
        secret_environment_variables: 'SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY_SECRET_REF }}'
        max_instances: 1
        event_trigger_type: 'google.pubsub.topic.publish'
        event_trigger_resource: '${{ secrets.GCP_PUBSUB_TRIGGER }}'
        event_trigger_service: 'pubsub.googleapis.com'
        
        
